baseurl = "https://xblzbjs.cn"
title = "行百里者半九十"
theme = "hugo-coder"
languageCode = "zh-cn"
defaultContentLanguage = "zh-cn"
paginate = 20

enableEmoji = true
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
pygmentsStyle = "solarized-dark256"

[params]
author = "行百里者半九十"
# avatarURL = "images/avatar.jpg"
colorScheme = "auto"
dateFormat = "January 2, 2006"
description = "xblzbjs的个人博客"
footerContent = "Enter a text here."
hideCopyright = false
hideCredits = false
hideFooter = false
info = "詩云：『行百里者半於九十。』此言末路之難也。"
keywords = "blog,developer,personal"
rtl = false
since = 2020
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = ["syntax.css"]
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

[params.googleTagManager]
id = "UA-192697137-1"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"


[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com"]


[[params.social]]
icon = "fa fa-github"
name = "Github"
url = "https://github.com/xblzbjs/"
weight = 1

[[params.social]]
icon = "fa fa-gitlab"
name = "Gitlab"
url = "https://gitlab.com/xblzbjs/"
weight = 2

[[params.social]]
icon = "fa fa-linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/xblzbjs/"
weight = 3

[[params.social]]
icon = "fa fa-rss"
name = "RSS"
rel = "alternate"
type = "application/rss+xml"
url = "https://xblzbjs.cn/index.xml"
weight = 4

[[languages.zh-cn.menu.main]]
name = "随笔"
weight = 1
url = "posts/"

[[languages.zh-cn.menu.main]]
name = "归档"
weight = 2
url = "archive/"

[[languages.zh-cn.menu.main]]
name = "关于"
weight = 3
url = "about/"

[[languages.zh-cn.menu.main]]
name = "学习资料"
weight = 4
url = "learning-materials/"


[page_not_found]
other = "Page Not Found"

[page_does_not_exist]
other = "Sorry, this page does not exist."

