# Url
baseurl      = "https://xblzbjs.cn"
title        = "xblzbjs"
languageCode = "zh-cn"
theme        = "hello-friend-ng"
# Dir Config
archetypeDir   = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"
# Build
buildDrafts = false   # 草稿
buildFuture = false   # 已过期的内容
buildExpired = false  # 将来包含publishdate的内容。
canonifyURLs = true   # 允许将相对url转换成绝对url
# Template
paginate     = 15
rssLimit     = 10 
# Language
defaultContentLanguage = "zh-cn"
# Google analytics
googleAnalytics = "UA-192697137-1"

enableEmoji    = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = true

  
[permalinks]
  # 文章url
  articles = "/articles/:year/:month/:title/"

[taxonomies]
    tag      = "tags"
    category = "categories"
    series   = "series"

# [frontmatter]
# date = ["date", "publishDate", "lastmod"]
# lastmod = [":git", "lastmod", "date", "publishDate"]
# publishDate = ["publishDate", "date"]
# expiryDate = ["expiryDate"]

[params]
  author          = "xblzbjs"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"



  # 在构建的时候是否需要将草稿打包进去,默认 false
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "xblzbjs的个人博客"
  keywords = "homepage, blog"
  images = [""]
  # 主页副标题
  homeSubtitle = "詩云：『行百里者半於九十。』此言末路之難也。"
  # enableSharingButtons = true
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  

[languages]
  [languages.zh-cn]
    title = "行百里者半九十"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">xblzbjs</a>'
    readOtherPosts = "Read other posts"

    [languages.zh-cn.params.logo]
      logoText = "xblzbjs"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # Social
  [[params.social]]
    name = "email"
    url  = "mailto:t710255295@gmail.com"
  [[params.social]]
    name = "github"
    url  = "https://github.com/xblzbjs"
  # [[params.social]]
  #   name = "twitter"
  #   url  = "https://github.com/xblzbjs"
  # [[params.social]]
  #   name = "stackoverflow"
  #   url  = "https://github.com/xblzbjs"
  
# Head
[[menu.main]]
  identifier = "about"
  name       = "关于"
  url        = "/about"
[[menu.main]]
  identifier = "book-list"
  name       = "书单"
  url        = "/book-list"
[[menu.main]]
  identifier = "articles"
  name       = "文章"
  url        = "/articles"
[[menu.main]]
  identifier = "home"
  name       = "主页"
  url        = "/"